### ISSUE TITLE
1click btn error: `Error: error:0308010C:digital envelope routines::unsupported`

### ISSUE THREAD

**Issue by zebapy** [keystonejs/keystone-6-railway-example#6]
the 1-click btn from readme is failing when i deploy to brand new railway account

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports.__webpack_modules__.15660.module.exports (/workspace/node_modules/next/dist/compiled/webpack/bundle4.js:111680:62)
    at NormalModule._initBuildHash (/workspace/node_modules/next/dist/compiled/webpack/bundle4.js:85092:16)
    at handleParseError (/workspace/node_modules/next/dist/compiled/webpack/bundle4.js:85146:10)
    at /workspace/node_modules/next/dist/compiled/webpack/bundle4.js:85178:5
    at /workspace/node_modules/next/dist/compiled/webpack/bundle4.js:85033:12
    at /workspace/node_modules/next/dist/compiled/webpack/bundle4.js:51096:3
    at iterateNormalLoaders (/workspace/node_modules/next/dist/compiled/webpack/bundle4.js:50937:10)
    at iterateNormalLoaders (/workspace/node_modules/next/dist/compiled/webpack/bundle4.js:50944:10)
    at /workspace/node_modules/next/dist/compiled/webpack/bundle4.js:50959:3
    at runSyncOrAsync (/workspace/node_modules/next/dist/compiled/webpack/bundle4.js:50853:11)
    at iterateNormalLoaders (/workspace/node_modules/next/dist/compiled/webpack/bundle4.js:50955:2)
    at processResource (/workspace/node_modules/next/dist/compiled/webpack/bundle4.js:50931:3)
    at iteratePitchingLoaders (/workspace/node_modules/next/dist/compiled/webpack/bundle4.js:50881:10)
    at iteratePitchingLoaders (/workspace/node_modules/next/dist/compiled/webpack/bundle4.js:50888:10)
```

**Comment by bladey** [comment]
Resolved as of Node engines and Keystone update, thanks @zebapy! - https://github.com/keystonejs/keystone-6-railway-example/commit/318794026ad9394c21019677d4568f9f2657b899
